//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace бисер_шоп
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tovar()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id_tovar { get; set; }
        public string title { get; set; }
        public string opisanie { get; set; }
        public int cena { get; set; }
        public int kolichestvo { get; set; }
        public string kartinka { get; set; }
        public int id_kat { get; set; }
    
        public virtual kategoriya kategoriya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
