//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace бисер_шоп
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int id_zakaz { get; set; }
        public int id_tovar { get; set; }
        public int id_user { get; set; }
        public int kolichestvo { get; set; }
    
        public virtual tovar tovar { get; set; }
        public virtual users users { get; set; }
    }
}
